// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDLGPTDIrOUK3MmeNqk02_m9tdBTIBgYM',
    appId: '1:792942328159:web:a544588f8df06b96f0deea',
    messagingSenderId: '792942328159',
    projectId: 'omgnicetv-be2f0',
    authDomain: 'omgnicetv-be2f0.firebaseapp.com',
    storageBucket: 'omgnicetv-be2f0.firebasestorage.app',
    measurementId: 'G-0KXR0Y9KMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpat_xGPd4uVnu2oj9FIjk_OHniuAn8XU',
    appId: '1:792942328159:android:d571b082ee9bcb3ef0deea',
    messagingSenderId: '792942328159',
    projectId: 'omgnicetv-be2f0',
    storageBucket: 'omgnicetv-be2f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5GZAfa3L7rHcXSfjNqi8WblQrCWgNG8',
    appId: '1:792942328159:ios:786d94de6853aeb9f0deea',
    messagingSenderId: '792942328159',
    projectId: 'omgnicetv-be2f0',
    storageBucket: 'omgnicetv-be2f0.firebasestorage.app',
    androidClientId: '792942328159-dc169bdea2i2e4o9rcp4teo4kbaii7n6.apps.googleusercontent.com',
    iosClientId: '792942328159-gqhp7a0tmkkkrdf2j1crmk06usuuktlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.omgniceEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ5GZAfa3L7rHcXSfjNqi8WblQrCWgNG8',
    appId: '1:792942328159:ios:786d94de6853aeb9f0deea',
    messagingSenderId: '792942328159',
    projectId: 'omgnicetv-be2f0',
    storageBucket: 'omgnicetv-be2f0.firebasestorage.app',
    androidClientId: '792942328159-dc169bdea2i2e4o9rcp4teo4kbaii7n6.apps.googleusercontent.com',
    iosClientId: '792942328159-gqhp7a0tmkkkrdf2j1crmk06usuuktlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.omgniceEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDLGPTDIrOUK3MmeNqk02_m9tdBTIBgYM',
    appId: '1:792942328159:web:7a9267455e262b7ef0deea',
    messagingSenderId: '792942328159',
    projectId: 'omgnicetv-be2f0',
    authDomain: 'omgnicetv-be2f0.firebaseapp.com',
    storageBucket: 'omgnicetv-be2f0.firebasestorage.app',
    measurementId: 'G-WSQQY5M3SP',
  );

}